# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .deployment import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "gcp-global-cloudrun",
  "mod": "index",
  "fqn": "pulumi_gcp_global_cloudrun",
  "classes": {
   "gcp-global-cloudrun:index:Deployment": "Deployment"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "gcp-global-cloudrun",
  "token": "pulumi:providers:gcp-global-cloudrun",
  "fqn": "pulumi_gcp_global_cloudrun",
  "class": "Provider"
 }
]
"""
)
